### PR TITLE
TDL-683: Added the support of stream campaigns.

### PR DESCRIPTION
**Pull request by dbshah1212**
# Description of change
- TDL-683: Support a stream for Campaigns

# Manual QA steps
 - Verify schema is generating in the catalog.json after discovery mode.
 - Verify Records are coming in expected values after sync mode. 
 
# Risks
 - No Risk
 
# Rollback steps
 - revert this branch

### CODE REVIEW

**Comment by dbshah1212** [comment]
Integration tests for the same will be added as part of Jira: https://jira.talendforge.org/browse/TDL-682

**Review by KAllan357 — APPROVED** [review]
This looks good if you rebase / merge master. That do_discover change is going to need to be addressed for all these open PRs.

**Comment by dbshah1212** [comment]
@KAllan357 I have rebased master.

**Comment by KAllan357** [comment]
We should leave the other schemas alone for now.

**Comment by dbshah1212** [comment]
Got it and back merged again, can you merge now @KAllan357?

**Pull request merged**
